-- PrimeHub 6.3 release bootstrap
-- Adds support for current server-spawned WORLD_DROP fruit Models while preserving 6.2 queue scoping.
local BASE_URL="https://raw.githubusercontent.com/softiksun5-hue/PrimeHub/main/release/PrimeHub-6.1.lua"

local function freshUrl(url)
    return url .. (string.find(url,"?",1,true) and "&cb=" or "?cb=")
        .. tostring(os.time()) .. "-" .. tostring(math.random(100000,999999))
end

local okBody,src=pcall(function()
    return game:HttpGet(freshUrl(BASE_URL),false)
end)
if not okBody or type(src)~="string" or #src<100 then
    error("[PrimeHub 6.3] Could not download fresh 6.1 base: "..tostring(src))
end

-- Promote public/runtime references to 6.3. License protocol stays pinned to 5.0 by the 6.1 base patch.
src=string.gsub(src,"6%.1","6.3")

-- Extend the readable-runtime patch generated by 6.1.
local marker="local ua=string.find(body,protocolNew,1,true)"
local runtimePatch=[==========[
uiPatch = uiPatch .. [========[
    -- PrimeHub 6.3: keep server queues scoped to the current PlaceId/Sea.
    local queueInitOld=[====[local function collectUnvisitedServers(maxCandidates)
    local state = loadRuntimeState()
    pruneVisitTimestamps(state)
    state.serverQueue = type(state.serverQueue) == "table" and state.serverQueue or {}
    state.serverQueueBuiltAt = tonumber(state.serverQueueBuiltAt) or 0
    state.serverQueueStrategy = tostring(state.serverQueueStrategy or "")
]====]
    local queueInitNew=[====[local function collectUnvisitedServers(maxCandidates)
    local state = loadRuntimeState()
    pruneVisitTimestamps(state)
    state.serverQueue = type(state.serverQueue) == "table" and state.serverQueue or {}
    state.serverQueueBuiltAt = tonumber(state.serverQueueBuiltAt) or 0
    state.serverQueueStrategy = tostring(state.serverQueueStrategy or "")
    state.serverQueuePlaceId = tostring(state.serverQueuePlaceId or "")
    local currentPlaceId = tostring(game.PlaceId or "")

    if state.serverQueuePlaceId ~= currentPlaceId then
        state.serverQueue = {}
        state.serverQueueBuiltAt = 0
        state.serverQueuePlaceId = currentPlaceId
        saveRuntimeStateImmediate(state)
        hopDebug("place changed -> server queue cleared for PlaceId=" .. currentPlaceId)
    end
]====]
    src=select(1,replaceLiteral(src,queueInitOld,queueInitNew,true))

    local queueSaveOld=[====[    state.serverQueue = queue
    state.serverQueueStrategy = HOP_QUEUE_STRATEGY
    saveRuntimeStateImmediate(state)]====]
    local queueSaveNew=[====[    state.serverQueue = queue
    state.serverQueueStrategy = HOP_QUEUE_STRATEGY
    state.serverQueuePlaceId = currentPlaceId
    saveRuntimeStateImmediate(state)]====]
    src=select(1,replaceLiteral(src,queueSaveOld,queueSaveNew,true))

    -- Current natural Blox Fruits spawns are Workspace.Model "Fruit " objects tagged WORLD_DROP,
    -- not legacy Tools. Teach the common scanner/ESP/pickup path to understand that format.
    local partOld=[====[local function getDroppedFruitPart(tool)
    if not tool or not tool.Parent or not tool:IsA("Tool") then return nil end
    local handle = tool:FindFirstChild("Handle")
    if handle and handle:IsA("BasePart") then return handle end
    if tool.Name == "Fruit " then
        local mesh = tool:FindFirstChildWhichIsA("MeshPart")
        if mesh then return mesh end
    end
    return nil
end]====]
    local partNew=[====[local function isServerWorldFruitModel(instance)
    if not instance or not instance.Parent or not instance:IsA("Model") then return false end
    if instance.Parent ~= workspace then return false end

    local rawName = tostring(instance.Name or "")
    local trimmedName = string.match(rawName, "^%s*(.-)%s*$") or rawName
    if string.lower(trimmedName) ~= "fruit" then return false end

    local handle = instance:FindFirstChild("Handle")
    if not handle or not handle:IsA("BasePart") then return false end

    local okTag, tagged = pcall(function()
        return game:GetService("CollectionService"):HasTag(instance, "WORLD_DROP")
    end)
    if okTag and tagged then return true end

    -- Fallback for delayed/missing CollectionService tag replication.
    local visual = instance:FindFirstChild("Fruit")
    local animator = instance:FindFirstChild("FruitAnimator")
    return visual ~= nil and visual:IsA("Model") and animator ~= nil
end

local function getDroppedFruitPart(tool)
    if not tool or not tool.Parent then return nil end

    if isServerWorldFruitModel(tool) then
        local handle = tool:FindFirstChild("Handle")
        if handle and handle:IsA("BasePart") then return handle end
        return nil
    end

    if not tool:IsA("Tool") then return nil end
    local handle = tool:FindFirstChild("Handle")
    if handle and handle:IsA("BasePart") then return handle end
    if tool.Name == "Fruit " then
        local mesh = tool:FindFirstChildWhichIsA("MeshPart")
        if mesh then return mesh end
    end
    return nil
end]====]
    src=select(1,replaceLiteral(src,partOld,partNew,true))

    local nameOld=[====[local function fruitNameFromTool(tool)
    if not tool or not tool:IsA("Tool") then return nil end
    local name = tostring(tool.Name or "")
    if name == "Fruit " then return name end]====]
    local nameNew=[====[local function fruitNameFromTool(tool)
    if not tool then return nil end
    if isServerWorldFruitModel(tool) then return "Fruit " end
    if not tool:IsA("Tool") then return nil end
    local name = tostring(tool.Name or "")
    if name == "Fruit " then return name end]====]
    src=select(1,replaceLiteral(src,nameOld,nameNew,true))

    local likeOld=[====[local function isFruitLikeTool(tool)
    if not tool or not tool:IsA("Tool") then return false end
    local name = tostring(tool.Name or "")
    if string.find(name, "Fruit", 1, true) then return true end
    if scanOriginalName(tool) then return true end
    if tool:FindFirstChild("EatRemote") then return true end
    return false
end]====]
    local likeNew=[====[local function isFruitLikeTool(tool)
    if not tool then return false end
    if isServerWorldFruitModel(tool) then return true end
    if not tool:IsA("Tool") then return false end
    local name = tostring(tool.Name or "")
    if string.find(name, "Fruit", 1, true) then return true end
    if scanOriginalName(tool) then return true end
    if tool:FindFirstChild("EatRemote") then return true end
    return false
end]====]
    src=select(1,replaceLiteral(src,likeOld,likeNew,true))

    local dropOld=[====[local function isDroppedFruit(tool)
    if not tool or not tool:IsA("Tool") then return false end
    if isInsidePlayerCharacter(tool) then return false end
    -- 5.1: no player-drop/server-only rejection. If it is a fruit-like world Tool, scan it.
    if not getDroppedFruitPart(tool) then return false end]====]
    local dropNew=[====[local function isDroppedFruit(tool)
    if not tool or not tool.Parent then return false end
    if isServerWorldFruitModel(tool) then
        return getDroppedFruitPart(tool) ~= nil
    end
    if not tool:IsA("Tool") then return false end
    if isInsidePlayerCharacter(tool) then return false end
    -- 6.3: collect both legacy world Tools and the current WORLD_DROP Model format.
    if not getDroppedFruitPart(tool) then return false end]====]
    src=select(1,replaceLiteral(src,dropOld,dropNew,true))

    src=select(1,replaceLiteral(src,
        [====[        tools = 0,
        fruitLike = 0,]====],
        [====[        tools = 0,
        worldModels = 0,
        fruitLike = 0,]====], true))

    src=select(1,replaceLiteral(src,
        [====[        if object:IsA("Tool") then
            stats.tools = stats.tools + 1
            local fruitLike = isFruitLikeTool(object)]====],
        [====[        local isTool = object:IsA("Tool")
        local isWorldModel = isServerWorldFruitModel(object)
        if isTool or isWorldModel then
            if isTool then
                stats.tools = stats.tools + 1
            else
                stats.worldModels = stats.worldModels + 1
            end
            local fruitLike = isFruitLikeTool(object)]====], true))

    src=select(1,replaceLiteral(src,
        [====[                local original = scanOriginalName(object)
                local label = tostring(object.Name)
                if original then label = label .. "{" .. original .. "}" end]====],
        [====[                local original = scanOriginalName(object)
                local label = isWorldModel and "SERVER FRUIT{WORLD_DROP}" or tostring(object.Name)
                if original then label = label .. "{" .. original .. "}" end]====], true))

    src=select(1,replaceLiteral(src,
        [====[            "%s mode=%s objects=%d tools=%d fruitLike=%d playerDrops=%d excludedHeld=%d targets=%d unlisted=%d dropFilter=%s allFruits=%s names=[%s]",
            tostring(debugTag or "scan"), stats.mode, stats.objects, stats.tools, stats.fruitLike,
            stats.playerDrops, stats.excludedHeld, stats.targets, stats.unlistedTargets, "OFF",]====],
        [====[            "%s mode=%s objects=%d tools=%d worldModels=%d fruitLike=%d playerDrops=%d excludedHeld=%d targets=%d unlisted=%d dropFilter=%s allFruits=%s names=[%s]",
            tostring(debugTag or "scan"), stats.mode, stats.objects, stats.tools, stats.worldModels, stats.fruitLike,
            stats.playerDrops, stats.excludedHeld, stats.targets, stats.unlistedTargets, "OFF",]====], true))

    src=select(1,replaceLiteral(src,
        [====[                root.CFrame = handle.CFrame + Vector3.new(0, tonumber(env.FlyOffset) or 5, 0)]====],
        [====[                local pickupOffset = isServerWorldFruitModel(fruit) and 2 or (tonumber(env.FlyOffset) or 5)
                root.CFrame = handle.CFrame + Vector3.new(0, pickupOffset, 0)]====], true))

    src=select(1,replaceLiteral(src,
        [====[                label.Text = tostring(fruit.Name) .. " (" .. tostring(distance) .. "m)"]====],
        [====[                local displayName = isServerWorldFruitModel(fruit) and "SERVER FRUIT" or tostring(fruit.Name)
                label.Text = displayName .. " (" .. tostring(distance) .. "m)"]====], true))
]========]

]==========]

local a,b=string.find(src,marker,1,true)
if not a then error("[PrimeHub 6.3] Runtime patch insertion point missing") end
src=string.sub(src,1,a-1)..runtimePatch..string.sub(src,a)

local fn,err=loadstring(src)
if not fn then error("[PrimeHub 6.3] Release compile failed: "..tostring(err)) end
local ok,result=pcall(fn)
if not ok then error("[PrimeHub 6.3] Runtime failed: "..tostring(result)) end
return result
